export const GET_TOPEVENT_REQUEST="GET_TOPEVENT_REQUEST";
export const GET_TOPEVENT_SUCCESS="GET_TOPEVENT_SUCCESS";
export const GET_TOPEVENT_FAILURE="GET_TOPEVENT_FAILURE";

export const GET_MAJOR_REQUEST="GET_MAJOR_REQUEST";
export const GET_MAJOR_SUCCESS="GET_MAJOR_SUCCESS";
export const GET_MAJOR_FAILURE="GET_MAJOR_FAILURE";