export const GET_TOPEVENT_REQUEST="GET_TOPEVENT_REQUEST";
export const GET_TOPEVENT_SUCCESS="GET_TOPEVENT_SUCCESS";
export const GET_TOPEVENT_FAILURE="GET_TOPEVENT_FAILURE";

export const GET_MAJOR_REQUEST="GET_MAJOR_REQUEST";
export const GET_MAJOR_SUCCESS="GET_MAJOR_SUCCESS";
export const GET_MAJOR_FAILURE="GET_MAJOR_FAILURE";

export const GET_NEWS_REQUEST="GET_NEWS_REQUEST";
export const GET_NEWS_SUCCESS="GET_NEWS_SUCCESS";
export const GET_NEWS_FAILURE="GET_NEWS_FAILURE";

export const GET_FEATURES_REQUEST="GET_FEATURES_REQUEST";
export const GET_FEATURES_SUCCESS="GET_FEATURES_SUCCESS";
export const GET_FEATURES_FAILURE="GET_FEATURES_FAILURE";

export const GET_UPCOMINGSUN_REQUEST="GET_UPCOMINGSUN_REQUEST";
export const GET_UPCOMINGSUN_SUCCESS="GET_UPCOMINGSUN_SUCCESS";
export const GET_UPCOMINGSUN_FAILURE="GET_UPCOMINGSUN_FAILURE";

export const GET_UPCOMINGSAT_REQUEST="GET_UPCOMINGSAT_REQUEST";
export const GET_UPCOMINGSAT_SUCCESS="GET_UPCOMINGSAT_SUCCESS";
export const GET_UPCOMINGSAT_FAILURE="GET_UPCOMINGSAT_FAILURE";